/*CREATE DATABASE TermProject;
go*/

/*USE TermProject;
go*/

USE pri0115;
go

CREATE TABLE [Language] (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	[ISO639-1Code] NVARCHAR(2) NOT NULL,
	[ISO639-3Code]  NVARCHAR(3) NOT NULL
);

CREATE TABLE [User] (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	LanguageID INTEGER NOT NULL,
	CONSTRAINT FK_USER_LANGUAGE FOREIGN KEY (LanguageID) REFERENCES [Language](ID)
);

CREATE TABLE DiagramType (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(MAX) NULL
);

CREATE TABLE NodeType (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	Initial BIT NOT NULL,
	[End] BIT NOT NULL,
	DiagramTypeID INTEGER NOT NULL,
	CONSTRAINT FK_NODETYPE_DIAGRAM FOREIGN KEY (DiagramTypeID) REFERENCES DiagramType(ID)
);

CREATE TABLE WorkSpace (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(256) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	CreationDate DATETIME NOT NULL,
	EditDate DATETIME NULL,
	UserID INTEGER NOT NULL,
	CONSTRAINT FK_WORKSPACE_USER FOREIGN KEY (UserID) REFERENCES [User](ID)
);

CREATE TABLE Graph (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(256) NOT NULL,
	WorkSpaceID INTEGER NOT NULL,
	CONSTRAINT FK_GRAPH_WORKSPACE FOREIGN KEY (WorkSpaceID) REFERENCES WorkSpace(ID)
);

CREATE TABLE Region (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,	
	[Text] NVARCHAR(256) NULL,
);

CREATE TABLE GraphNode (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,	
	[Text] NVARCHAR(256) NOT NULL,
	GraphID INTEGER NOT NULL,
	NodeTypeID INTEGER NOT NULL,
	RegionID INTEGER NULL,
	CONSTRAINT FK_GRAPHNODE_REGION FOREIGN KEY (RegionID) REFERENCES Region(ID),
	CONSTRAINT FK_GRAPHNODE_NODETYPE FOREIGN KEY (NodeTypeID) REFERENCES NodeType(ID),
	CONSTRAINT FK_GRAPHNODE_GRAPH FOREIGN KEY (GraphID) REFERENCES Graph(ID)
);

CREATE TABLE GraphEdge (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,	
	FromNodeID INTEGER NOT NULL,	
	ToNodeID INTEGER NOT NULL,	
	[Text] NVARCHAR(256) NOT NULL,
	CONSTRAINT FK_GRAPHEDGE_GRAPHNODE_FROM FOREIGN KEY (FromNodeID) REFERENCES GraphNode(ID),
	CONSTRAINT FK_GRAPHEDGE_GRAPHNODE_TO FOREIGN KEY (ToNodeID) REFERENCES GraphNode(ID),
);


/*CLEAN UP*/
/*
USE TermProject;
go

DROP TABLE GraphEdge;
DROP TABLE GraphNode;
DROP TABLE Region;
DROP TABLE Graph;
DROP TABLE WorkSpace;
DROP TABLE NodeType;
DROP TABLE DiagramType;
DROP TABLE [User];
DROP TABLE [Language];

USE [master];
go
DROP DATABASE TermProject;
go
*/
